services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tron_service
    command: "poetry run python3 main.py"
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8080"
    networks:
      - tron-network

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - tron-network
    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  tron-network:
    driver: bridge

volumes:
  postgres_data:
